services:
  iristraining:
    #image: irepo.intersystems.com/intersystems/irishealth:2023.1.4.580.0
    build: .
    init: true
    container_name: iris4h
    ports:
       - "8082:1972"
    environment:
      - TZ=JST-9
    volumes:
      - ./temp:/temp

  webgw:
    image: containers.intersystems.com/intersystems/webgateway:2024.1
    container_name: webgw1
    init: true
    ports:
      - 8080:80
      - 8443:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway:/webgateway-shared